name: Build flutter release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      #   with:
      #     channel: beta #supposedly required for web

      # - name: Enable Flutter Web
      #   run: flutter config --enable-web

      # - name: Download Dependencies
      #   run: flutter pub get
      # - run: flutter test

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /